---
title: "Gov 50 Final Project"
author: "Owen Ebose"
description: "Owen's final project on the relationship between employment class and democratic participation."
output:
  distill::distill_article:
    self_contained: false
---

*(Older milestones below)*

## Milestone 3

```{r}
library(tidyverse)
library(stringr)

#loading data

#census_raw <- read_csv("nov22pub (1).csv")

#selecting variables 

#census <- census_raw |>
  #select(employment_class=PEIO1COW, voted=PES1, income_code=HEFAMINC)

#write.csv(census,"census.csv")

census <- read_csv("census.csv")

#replacing coded values

census$employment_class <- census$employment_class |>
  case_match(1 ~ "Federal gov't",
             2 ~ "State gov't",
             3 ~ "Local gov't", 
             4 ~ "For profit",
             5 ~ "Non profit",
             6 ~ "Self-employed Inc.",
             7 ~ "Self-employed Non-Inc.",
             8 ~ "Unpaid",
             .default="other")

census$voted <- census$voted |>
  case_match(1 ~ "yes",
             2 ~ "no",
             .default="other")

census$household_income <- census$income_code |>
  case_match(-1 ~ "other",
             1 ~ "less than 5",
             2 ~ "5 to 7.499",
             3 ~ "7.5 to 9.999", 
             4 ~ "10 to 12.499",
             5 ~ "12.5 to 14.999",
             6 ~ "15 to 19.999",
             7 ~ "20 to 24.999",
             8 ~ "25 to 29.999",
             9 ~ "30 to 34.999",
             10 ~ "35 to 39.999",
             11 ~ "40 to 49.999",
             12 ~ "50 to 59.999",
             13 ~ "60 to 74.999",
             14 ~ "75 to 99.999",
             15 ~ "100 to 149.999",
             16 ~ "150 or more")

#calculating turnout rates by employment class

employment_turnout <- census |>
  group_by(employment_class, voted) |>
  summarize(n = n()) |>
  mutate(prop = n / sum(n) *100) |>
  filter(voted == "yes") |>
  select(-voted, -n) |>
  mutate(prop = round(prop, digits = 2)) |>
  rename(turnout = prop)

knitr::kable(employment_turnout)

#plotting turnout rates by employment class

employment_turnout_plot <- employment_turnout |>
  ggplot(mapping = aes(x = fct_reorder(employment_class, turnout), y = turnout)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Impact of Employment Class on Electoral Participation",
    x = "Employment class",
    y = "Turnout (%) in 2022 national elections",
    caption = "Note: Employment class categorizes workers according to the type of ownership of the employing organization. This variable identifies whether the respondent is self-employed, works in the private sector, or in government. (U.S. Census Bureau)"
  ) +
  theme_classic() +
  theme(plot.margin = margin(b = 10))

wrapped_caption <- str_wrap("Note: Employment class categorizes workers according to the type of ownership of the employing organization. This variable identifies whether the respondent is self-employed, works in the private sector, or in government. (U.S. Census Bureau)", width = 112)

employment_turnout_plot <- employment_turnout_plot + labs(caption = wrapped_caption)

employment_turnout_plot

#calculating turnout rates by income group 

income_turnout <- census |>
  group_by(household_income, voted) |>
  summarize(n = n()) |>
  mutate(prop = n / sum(n) *100) |>
  filter(voted == "yes") |>
  select(-voted, -n) |>
  mutate(prop = round(prop, digits = 2)) |>
  rename(turnout = prop)

knitr::kable(income_turnout)

#plotting turnout rates by income group

income_turnout_plot <- income_turnout |>
  ggplot(mapping = aes(x = fct_reorder(household_income, turnout), y = turnout)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Impact of Household Income on Electoral Participation",
    x = "Annual household income (in thousands)",
    y = "Turnout (%) in 2022 National Elections"
  ) +
  theme_classic()

income_turnout_plot

```

## Milestone 2

Does one's class of work affect their degree of democratic participation? I plan to investigate how work conditions influence the ability or willingness of workers to vote. I hypothesize that those who are the most inclined to participate (1) work in settings where politics are involved or discussed and (2) work less hours. Proximity to politics can inspire or pressure one to participate. A less demanding work schedule allows one the time needed to engage in politics. I expect to find, therefore, that government and non-profit employees and the self-employed participate the most: government and non-profit employees due to their proximity to politics, and the self-employed due to their control over their schedules. In election years, the Current Population Survey conducted by the U.S. Census Bureau asks tens of thousands of Americans whether or not they voted in the most recent national election. The latest edition of the survey, based on the 2022 elections, features 264,707,835 responses. On top of vote status, the survey asks respondents to report their "class" of work, one of six categories: employment by (1) the federal government, (2) a state government, (3) a local government, (4) a private for-profit company, (5) a private non-profit entity, or (6) no one (i.e., self-employed). I can compare the turnout rates of each group in the 2022 national elections to determine which participated the most. In other words, the explanatory variable of interest is "class" of work as defined by the Census Bureau and the outcome variable of interest is whether or not the respondent voted (coded "1" for voted and "2" for not voted in the dataset). If my hypothesis is correct, I will observe that workers of classes 1, 2, 3, and 5 (government and non-profit employees) and 6 (the self-employed) turned out to vote at the highest rates in 2022. Workers of class 4 (for-profit employees), who are by far the largest group in the dataset, will have turned out the least.

Link to the dataset: <https://data.census.gov/mdat/#/search?ds=CPSVOTING202211&cv=HEFAMINC,PES1&rv=PEIO1COW&wt=HWHHWGT>

## Project thoughts

I am interested in exploring the impact of British Commonwealth membership on political attitudes, nationalism, and democratic participation. Do citizens of countries that remove the Monarch as their head of state develop a greater sense of national pride and therefore a greater desire to participate politically? I can measure this using voter turnout rates and surveys of populations that have experienced such a transition.
